# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Currency' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Currency

  target 'Currency-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Currency-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Currency-tvOS



end
